#+TITLE: PyQt
#+KEYWORDS: python GUI qt
#+OPTIONS: H:2 toc:2 num:3 ^:nil
#+SETUPFILE: ~/github/notes/org-html-themes/setup/theme-readtheorg.setup

* modules
** QtCore
   SIGNAL, QTime, QTimer
*** Qt
    QT.SplashScreen
** QtGui
*** QApplication
*** QDialog
    - setLayout
    - connect
*** Widgets
    - QLable
    - QTextBrowser: a read-only multi-line text box that can display both plain text and HTML
    - QLineEdit: a single-line editable text box that displays plain text
    - QDial
    - QSpinBox
    # - dock widgets: need to explicitly pass a parent to them
*** Layouts
    QVBoxLayoutx

* Dialogs
** Dumb Dialogs
   #+BEGIN_VERSE
   We define a “dumb” dialog to be a dialog whose widgets are set to their initial
   values by the dialog’s caller, and whose final values are obtained directly from
   the widgets, again by the dialog’s caller.

   Dumb dialogs are normally modal dialogs with an “accept” button (e.g., OK ) and a
   “reject” button (e.g., Cancel ).
   #+END_VERSE
** Standard Dialogs
** Smart Dialogs

* Signal

  - short-circuit
    #+BEGIN_VERSE
    If we use the SIGNAL() function with an identifier but no parentheses, we are
    specifying a short-circuit signal.
    #+END_VERSE

  - Qt/Python signal
    #+BEGIN_VERSE
    If we use the SIGNAL() function with a signalSignature (a possibly empty paren-
    thesized list of comma-separated PyQt types), we are specifying either a
    Python or a Qt signal. (A Python signal is one that is emitted in Python code; a
    Qt signal is one emitted from an underlying C++ object.
    #+END_VERSE
