@startuml
start
:新黄浦一年看情况;
if (情况理想？) then (是)
        :火车站附近找置换;
else (否)
        fork
                :出国;
        fork again
                :回三小;
        fork again
                :全市置换;
        end fork
endif
end
@enduml
