#+TITLE: Alpha Factors
#+OPTIONS: H:3 toc:2 num:2 ^:nil
#+AUTHOR: ChrisChen
#+EMAIL: ChrisChen3121@gmail.com
* Overview
  - The search for alpha factors is essentially the search for *deviations* from the efficient market hypothesis.

** Processing Techniques
   Techniques to turn the alpha vectors into signals.
   - Sector neutralization
   - Ranking
   - Z-scoring
   - Smoothing
   - Conditioning

** Goal
   Use risk models to *neutralize* exposure to risk factors, so that
   remaining portfolio returns and volatility are due to alpha factors.

** Alpha Model
   An algorithm that transforms data into numbers associated with each asset.

* Ideas
** Academic Papers
*** Why
   1. Idea generation
   1. Baseline for comparison
   1. New methods
   1. New sources of data / novel ways to work with data

*** Where
    - General interest journals
    - Investment journals
    - Open source journals

*** How
    - Use citations to find other related works.
    - Focus on papers that can be replicated.
    - Check if methodology is practical.


* Standardization
  - *Ranking* is a broadly useful method for making data analysis more *robust*.
    - Makes our alpha vectors more robust against outliers and noise.
    - Best to use when all alpha vectors are generated from the same stock universe
  - *Z-Score*
    - Not robust against outliers and noise
    - Useful to apply ranking and then z-scoring, when alpha vectors are generated from different stock universes.
  - Smoothing
    - Rolling window average
    - Weighted moving average: $\alpha_{t,smoothed}=\frac{(T\times \alpha_t)+((T-1)\times \alpha_{t-1})+\cdots+(1\times{\alpha_{t-T+1}})}{T+(T-1)+\cdots+1}$

* Neutralization
  The most significant risk factors are market risk and sector risk
  1. Neutralize by market (market mean)
  1. Neutralize by sector (sector mean)
  1. Repeat for all sectors in stock universe
