#+TITLE: Terminologies
#+OPTIONS: H:1 toc:1 num:1 ^:nil
#+AUTHOR: ChrisChen
#+EMAIL: ChrisChen3121@gmail.com

- Stock :: An asset that represents ownership in a company. A claim on part of a corportation's assets and earnings. There are two main types, common and preferred.
- Share :: A single share represents partial ownership of a company relative to the total number of shares in existence.
- Common Stock :: One main type of stock; entitles the owner to receive dividends and to vote at shareholder meetings.
- Preferred Stock :: The other main type of stock; generally does not entail voting rights, but entitles the owner to a higher claim on the assets and earnings of a company.
- Dividend :: A partial distribution of a company's profits to shareholders.
- Capital Gains :: Profits that result from the sale of an asset at a price higher than the purchase price.
- Security :: A tradable financial asset.
- Debt Security :: Money that is owed and must be repaid, like government or corporate bonds, or certificates of deposit. Also called fixed-income securities.
- Derivative Security :: A financial instrument whereby its value is derived from other assets.
- Equity :: The value of an owned asset minus the amount of all debts on that asset.
- Equity Security :: A security that represents fractional ownership in an entity, such as stock.
- Option Contract :: A contract which gives the buyer the right, but not the obligation, to buy or sell an underlying asset at a specified price on or by a specified date
- Futures Contract :: A contract that obligates the buyer to buy or the seller to sell an asset at a predetermined price at a specified time in the future
- Total Market Capitalization :: The dollar value of a company's outstanding shares.
- Inflection Point :: 拐点
- Cross-sectional Analysis :: Cross-sectional analysis looks at data collected at a single point in time, rather than over a period of time. OPP Time-series Analysis
- Data-snooping(P-hacking) :: The misuse of data analysis to find patterns in data by performing many statistical tests on the data and only reporting those that come back with significant results.
- Backtesting :: The process of rigorously simulating the entire flow in an automated fashion using historical data.
- Alpha :: An expression that outputs a vector of values which are proportional to the size of the position you will take on each asset.
  - The procedure that produces the ranks. The ranks themselves make up the *Alpha Vector*.
- Volume :: Number of shares traded.
- Turnover :: Volume Traded $\times$ Price Per Share
- Contrarian Strategies :: seek to identify sudden price movements and trade against such movements.(minute level data, risky)
- Lookahead Bias :: Incorporating the information from the future.(this misuse often make your results look better)
- Signal to Noise Ratio :: The signal is the meaningful part of input data. The noise is the random part of input data. The ratio is low for finance, the output models tend to *overfit* the data.
- Quartiles :: Quartiles are the three dividing lines that divide the data into four groups.
