#+TITLE: NCE3
#+KEYWORDS: NCE
#+OPTIONS: H:2 toc:1 num:2 ^:nil
#+SETUPFILE: ../../configOrg/level1.org
* A puma at large
** words
*** leopard [lepəd]
#+BEGIN_VERSE
a large animal of the cat family, with yellow fur and black spots, which lives in Africa and South Asia
一般豹统一称为leopard
#+END_VERSE
**** puma
a large American wild animal of the cat family, with yellowish-brown or greyish fur
**** jaguar
a large cat (Panthera onca) chiefly of Central and South America that is larger and stockier than the leopard and is brownish yellow or buff with black spots
*** possession
**** in sb's possession
**** in the possession of something
**** take possession of something
start having or using it
*** oblige
feel obliged to = be obliged to
** notes
*** at large
free of restraint or confinement
*** on a fishing trip
#+BEGIN_VERSE
on + n. 强调动作正在进行
on the rise
on the match
#+END_VERSE
*** take sth. seriously
* Thirteen equals one
** words
*** arm
- to provide all the information, skills, or equipment you need to do something
- arm sb. with sth.(sb. be armed with sth.) →equip sb. with sth.
*** grocer
someone who owns or works in a shop that sells food and other things used in the home
*** equal
**** be equal to sth.
#+BEGIN_VERSE
to have the ability to deal with a problem, piece of work etc successfully
= be up to
#+END_VERSE
*** start
#+BEGIN_VERSE
a sudden movement of your body, usually caused by fear or surprise
eg: Ted woke up with a start and felt for the light switch.
#+END_VERSE
** notes
*** catch sight of
瞥见
*** get used to doing sth./sth.
i.e
**** be used to
**** be accustomed to
**** get accustomed to
*** ever since
continuously since the time mentioned
*** Whatever are you doing
Whatever 加强语气： 你究竟在干什么？
*** Still,
Still 用于句首，表转折。
*** in 特殊用法(in the torchlight)
**** used with negatives or with ‘first’ to say how much time has passed since the last time something happened
eg: It was the team’s first win in eighteen months.
**** wearing something
eg: He looked very handsome in his uniform.
**** used to talk about the state or situation of something or someone
eg: I hear that their marriage is in trouble.
**** used to talk about the shape, arrangement, or course of something or someone
#+BEGIN_VERSE
eg: She slept curled up in a ball.  
Can you walk in a straight line?
#+END_VERSE
**** used to say how something is done or happens
#+BEGIN_VERSE
eg:a short note scribbled in pencil
Her parents always talk to her in German.
She shouted my name in a harsh voice.
#+END_VERSE

* A unknown goddess
** words
*** archaeologist
考古学家
| Anthropologist | 人类学家 |
| Philosopher    | 哲学家   |
| Geologist      | 地质学家 |
| Psychologist   | 心理学家 |
| Biologist      | 生物学家 |
| Physicist      | 物理学家 |
| Chemist        | 化学家   |
| Economist      | 经济学家 |
*** promontory [ˈprɒməntəri]
a long narrow piece of land which sticks out into the sea
*** prosperous adj.
rich and successful
*** sacred [ˈseɪkrəd] adj.
relating to a god or religion →holy
*** classical vs. classic
*** rest on/upon sth.
- to depend on something

eg: Success in management ultimately rests on good judgment.
*** graceful
#+BEGIN_VERSE
behaving in a polite and pleasant way
→elegant 优雅 可表达graceful类似的意思
an idea or a plan that is elegant is very intelligent yet simple:
#+END_VERSE
*** reconstruct
- construct
- constructive
- construction
*** enjoy
- to have a particular ability or advantage

eg: These workers enjoy a high level of job security.
*** beneath [bɪˈniːθ]
in or to a lower position than something, or directly under something
*** statue
an image of a person or animal that is made in solid material such as stone or metal and is usually large → sculpture
** notes
*** for 状语从句
- 重点是对主句的附加说明和解释。because引导的突出原因。

eg: The day broke for the birds were singing.
*** happen to
- to occur by chance — often used with it

eg: It happened to be among remains.
*** turn out
- to happen in a particular way, or to have a particular result, especially one that you did *not expect*
#+BEGIN_VERSE
eg: It was a difficult time, but eventually things turned out all right.
That guy turned out to be Maria’s second cousin.
*As it turned out* (=used to say what happened in the end), he passed the exam quite easily.
#+END_VERSE
- despite
→ in spite of
* The double life of Alfred Bloggs
** words
*** manual
#+BEGIN_VERSE
manual worker = blue collar
pink collar(female blue collar)
#+END_VERSE
*** sacrifice
- v.
#+BEGIN_VERSE
sacrifice A to/for B
sacrifice A to do B
#+END_VERSE
- n.
make some sacrifice
*** privilege
特权优待 
a special advantage that is given only to one person or group of people
eg: Parking on this road is the privilege of the residents.
*** shower
淋浴
- bath 盆浴
take a shower/bath
#+BEGIN_VERSE
bath-tub 浴缸
run a bath 放洗澡水
#+END_VERSE
*** secret |siːkrɪt|
**** 保密说法
- keep a secret
- hold one's tongue about
- button up one's lip
- This is only between you and me
- This can never go out of this room
**** 泄密说法
- reveal the secret
- let the secret out
- let the cat out of the bag
**** 词组
do sth. in secret 偷偷做某事
**** adj. 
keep ... secret from  sb.

** notes
*** these days
= nowadays = presently = currently = for the time being
*** give rise to
导致
*** worth
- be worth + money
- be worth doing

