#+TITLE: Learn Cardio
#+KEYWORDS: cardio, EKG
#+OPTIONS: H:3 toc:3 num:3 ^:nil
#+SETUPFILE: ~/github/notes/org-html-themes/setup/theme-readtheorg.setup
#+LaTeX: t
* Heart
** cardio cells
#+BEGIN_VERSE
Cardiac cells, in their resting state, are electrically
polarized; that is, their insides are negatively charged
with respect to their outsides.
#+END_VERSE

** sinus node (Sinoatrial node)(SA)
#+BEGIN_VERSE
Each cycle of cardiac contraction and relaxation is initiated by
spontaneous depolarization of the sinus node. This event is not
seen on the EKG.
#+END_VERSE
** atrioventricular node(AV)
** Atrial
** Ventricular
** Left Bundle Branch
*** Left Posterior Fascicle
*** Left Anterior Fascicle
*** Septal Fascicle
* Graph
** P Wave
#+BEGIN_VERSE
The P wave records atrial depolarization and contraction.
The first part of the P wave reflects right atrial
activity; the second part reflects left atrial activity.

Atrial repolarization is not seen.
There is a wave of atrial repolarization as well,
but it coincides with ventricular depolarization
and is hidden by the much more prominent QRS complex.
#+END_VERSE
- The amplitude of the P wave does not normally exceed 0.25 mV (2.5 mm, or two and one half small squares) in any lead
- The P wave is small and usually positive in the left lateral and inferior leads
- The P wave amplitude is usually most positive in lead II and most negative in lead aVR
** PR segment
A brief pause when the electrical current reaches the AV node and the EKG falls silent
** QRS interval
#+BEGIN_VERSE
The first part of the ventricles to be depolarized is
the interventricular septum[fn:1]. Ventricular depolarization
generates the QRS complex.

The right and left ventricles then depolarize at about
the same time, but most of what we see on the EKG
represents left ventricular activation because the muscle
mass of the left ventricle is about three times that of
the right ventricle.
#+END_VERSE
** T Wave
#+BEGIN_VERSE
The T wave records ventricular repolarization.
The amplitude, or height, of a normal T wave is one third to two thirds that of the corresponding R wave.
#+END_VERSE

** Segements and Intervals
- The PR interval measures the time from the start of atrial depolarization to the start of ventricular depolarization.
  - The PR interval normally lasts from 0.12 to 0.2 seconds (3 to 5 mm on the EKG paper).
- The PR segment measures the time from the end of atrial depolarization to the start of ventricular depolarization.
- The ST segment records the time from the end of ventricular depolarization to the start of ventricular repolarization.
- The QT interval measures the time from the start of ventricular depolarization to the end of ventricular repolarization.
  - The duration of the QT interval is proportionate to the heart rate
- The QRS interval measures the time of ventricular depolarization.
  - Normal septal Q waves have an amplitude of not greater than 0.1 mV.
  - A normal QRS interval, representing the duration of the QRS complex, is 0.06 to 0.1 seconds in duration.
* Footnotes

[fn:1] interventricular septum, the wall of muscle separating the right and left ventricles
