#+TITLE: Financial Market
#+KEYWORDS: finance
#+OPTIONS: H:4 toc:2 num:3 ^:nil
#+LaTeX: t
#+LANGUAGE: en-US
#+AUTHOR: ChrisChen
#+EMAIL: ChrisChen3121@gmail.com
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+SETUPFILE: ../../org-templates/level-1.org
* Conceptions
** VAR(value at risk)
   *Value at risk* is usually quoted in units of $ for a given probability and time horizon

   Ex: 1% one-year VAR of $10 million means 1% chance that a portfolio will lose $10 million in a year

** Stress tests
   The stress test is a test usually ordered by government to see
   how some firm will stand up to a financial crisis.

** Cauchy distribution
   Fat-tailed

* Strategy Benchmark
** Expected return
   $$return = \frac{value_{end}}{value_{start}} - 1 $$
*** long-period return 2 short-period avg return(using geomean)
    Number of period is denoted by *n*.
    $$short\_avg = \sqrt[n]{1+total\_return} - 1$$

** Daily return
   $$rets_i = \frac{value_i}{value_{i-1}} - 1 $$

** Sharpe ratio
   $$Sharpe = \frac{E - R_f}{\sigma} $$
   - $R_f$: risk free return
*** from period returns
    $$Sharpe = sqrt(k) * \frac{mean(period\_rets)}{std(period\_rets)}$$
    - k: trading periods in one year. 250 for days, 12 for month
** Sortino ratio
   only count volatility when it's downward

** Max drawdown
** Jensen's alpha
* Company value
** Market capital
** Discount ratio(present value)
** Book value
   A company's book value is its total assets minus intangible assets and liabilities
* CAPM
** Return on stock has two components
   $$r_i = \beta_i \cdot r_m + \alpha_i$$
*** Systematic(the market) $\beta$
*** Residual $\alpha$
** Market return
   Risk free rate of return + excess return
* Efficient Markets Hypothesis
** Weak
   Current prices reflect all past publicly available information.
   - Prohibits profit from T.A
** Semi-Strong
   Weak + prices instantly change to reflect new public information
   - Prohibits profit from T.A & F.A
** Strong
   Semi-Strong + prices instantly reflect even hidden or "insider" information
   - Prohibits profit from insider information
* Analysis
** Technical Analysis
   - Prices and volume only
** Fundamental Analysis
   - Financial statements
   - P/E ratios, cash on hand, dividends
* Information Source
  - Price/Volume: The markets
  - Fundamental: SEC filings
  - News: Exogenous sources
* Insurance
** Risk Pooling
   *Risk Pooling* is the source of all value in insurance.

   If *n* policies, each has independent probability *p* of a claim,
   then the number of claims follows the binomial distribution. The
   standard deviation of the fraction of policies that result in a claim is
   $\frac{\sqrt{np(1-p)}}{n}=\sqrt{\frac{p(1-p)}{n}}$
