#+TITLE: 海龟交易法则
#+KEYWORDS: turtle, trading
#+OPTIONS: H:4 toc:2 num:3 ^:nil
#+LaTeX: t
#+LANGUAGE: zh-CN
#+AUTHOR: ChrisChen
#+EMAIL: ChrisChen3121@gmail.com
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+SETUPFILE: ../../org-templates/level-1.org
* 认知偏差(cognitive bias)
** 损失厌恶(loss aversion)
   多数人对同风险下同数量的损失比收益敏感(prospect theory)
** 沉没成本效应(sunk costs effect)
   更重视已花掉的钱，而不是未来可能要花的钱
** 处置效应(disposition effect)
   早早兑现利润，却让损失持续下去(prospect theory)
** 结果偏好(outcome bias)
** 近期偏好(recency bias)
** 锚定效应(anchoring)
   过于依赖容易获得的信息
** 潮流效应(bandwagon effect)
** 小数定律(the law of small numbers)
   从太少的信息中得出没有依据的结论
* 趋势策略
** Donchian Channels
   A moving average indicator developed by Richard Donchian. It plots the
   highest high and lowest low over the last period time intervals.
** 支撑和阻力
   趋势突破的支撑和阻力主要来源于三种认知偏差：锚定效应，近期偏好以及处置效应。一个近期的新高新低变成新的锚点。

* 策略评测
** 回报量化
*** 几何平均回报率(geometric average return)
    投资期间的平均化复利率
*** 年平均回报率(average one year trailing return)
*** 平均月度回报率(average monthly return)

** 风险量化
*** 回报标准差
*** 最大回撤(max drawdown)
*** 最大回撤周期
    衡量衰落的恢复速度
*** R 平方值
    实际投资回报率与平均复合增长率的吻合程度

** 风险回报综合指标
*** 夏普比率(sharpe ratio)
    夏普比率流行的劣势：把回报的稳定性当成风险水平的唯一衡量标准
*** MAR 比率(MAR ratio)
    MAR 比率等于年均回报率除以最大的回撤幅度
*** R-multiple
    R 乘数等于一笔交易的利润除以这笔交易的风险投入

** 其他
*** MAE(maximum adverse excursion)/MFE(maximum favorable excursion)
    最大不利变动幅度和最大有利变动幅度
    - 用处：衡量一个入市信号的优势

* 资产管理
** ATR(average true range)
   The true range indicator is the greatest of the following: current high less the current low,
   the absolute value of the current high less the previous close and the absolute value of the
   current low less the previous close. The average true range is a moving average, generally 14 days,
   of the true ranges.
   - 用处：根据每日波动幅度调整头寸规模。
