#+TITLE: Happier
#+OPTIONS: H:2 toc:1 num:1 ^:nil
* What is happiness
  *Pleasure* and *meaning* are central to living a happy and fulfilled life.
  - *Meaningful*: To set appropriate goals

** Four archetypes of happiness
   - rat-race archetype
     - Pursues the future benefit and neglects present benefit.
     - The painful path must be taken before being able to attain future happiness
   - hedonism archetype: Opposite to the rat-race archetype
     - Only values present benefit and ignores future benefit.
   - nihilism archetype
     - Neither enjoys what they have in the present, nor have any hope for the future.
     - Have lost faith and desire in life.
   - happiness archetype

* Meaning, Pleasure, Strength(MPS)
  Begin by writing three answers:
  - What do I find meaningful? e.g. writing, music, working with kids, solving problems.
  - Where do I find pleasure? e.g. horseback riding, reading, music and time with children.
  - Where are my strengths? e.g. empathy, problem solving and getting along with kids.

  Notice the overlaps -- working with kids for example. Your strengths might be highly organized,
  enjoy planning and love to travel. Then, you might decide to become a music teacher.

* Relationships
  The more effort you put into cultivating meaningful relationships in your life, The happier you
  will be. Key points:
  - Sharing joy is pleasurable experience
  - Sharing sorrow can be comforting during painful times.
  - A hedonistic relationship that's solely focused on pleasure will rapidly lose its meaning.
  - A relationship based on shared values but lacking pleasure will also struggle.

* At work
  - Creating flow experiences. Let flow happen *naturally*.
    - *Flow*: immersed in an experience.
    - By Adjusting our work tasks to make their level of difficulty match our personal skills.
  - Using the MPS process to find a job or make life decisions.
  - Developing/Cultivating a sense of purpose.

* In life
  - *Cultivating* love over finding love
  - Creating an invisible circle of happiness around ourselves.
  - Cultivating "happiness boosters" as a daily habit. Finding small habits that provide us happy experiences.
