#+TITLE: How To Read A Book
#+OPTIONS: H:1 toc:1 num:1 ^:nil
* Why should we read?
  - For entertainment and access to information
  - To increase understanding of a certain topic
  - *To expand the mind*

* Four Levels of Reading
  - Elementary reading
  - *Inspectional reading* involves systematic skimming or prereading.
  - *Analytical reading* involves comprehensive and complete reading.
  - Syntopical reading

* Inspectional Reading
  - Systemmatic skimming: Title -> Preface -> Table of Contents -> Index & Publisher's blurb.
  - Reading through the book quickly. (*without stopping*)

* Analytical Reading
  Three stages:
  - Finding out what a book is talking about
    1. Identify the type of the book. Theoretical?Practical?Others?
    1. Discover the theme of the book, and then summarize the entirety of its main contents.
    1. Find out the structure of the book and draw its mind map or outline. (not necessarily follow its original structure)
    1. Find out the questions the author is trying to ask or solve.

  - Understanding the specific content of the book
    1. Find the most important *keywords* in the book and understand the precise meaning behind them.
    1. Highlight the important sentences and discover its main idea.
    1. Organize the author's points in order and use notes to reconstruct the chain of causality.
    1. To determine which questions the author has indeed solved.

  - Fairly judge a book

* Syntoptical Reading
  Involve selecting and reading related books covering the same topic in order to obtain a comprehensive understanding of an issue.
  1. Use inspectional reading to find relevant passages.
  1. Understand the answers of different authors to the same question.
  1. Clarify the problem and list the questions that interest you most.
  1. Define the issues in which we are discussing.
  1. Analyze and discuss, understand the key points of each answer.

* How to Read Different Genres
  - *Practical books* tell us how to do something
  - Fictional literature
  - Theoretical Books
    - Historical bookes: 1. read more than one book on the event 2. focus on understanding the reason behind the history
    - Scientific books: General readers can understand most of these books through analytical reading.
    - Philosophical books: It is important for us to understand the questions the author intends to answer.
