#+title: Parenting
#+OPTIONS: H:2 toc:1 num:2 ^:nil
* Between Parent and Child
** Barriers
  - The lack of professional knowledge about raising a child
  - Children's difficulty *expressing their feelings* and *controlling negative emotions*
  - The *misrepresented word* of parents. When parents say negative and critical words out of anger, children will take them seriously.

** Methods
  - Discovering and *empathizing* with children's feelings and expressing their emotions in a reasonable way.
  - Actively teaching correct behaviors and heavily constraining bad behaviors.
  - Guiding children to motivate and evaluate themselves positively.
  - Allowing children to have *a voice* and *a choice* when limitations are set.

* How to Talk so Kids Will Listen
** Acceptance
   Acknowledging Kids' Feelings
   - When facing emotional kids, the first step for parents is to express *acceptance* and *empathy*.
   - Stopping kids' actions does not *conflict with* accepting their feelings

** Praising
   The Highest Level of Parenting
   - *Descriptive* praise is more effective than evaluative praise
   - Sum it up in a word to make kids feel fulfilled
   - Turning mistakes into *discoveries* is a method of praising

** Cooperation
   When Having a Disagreement, Make It Win-Win
   - *Blame-free* language makes kids more willing to cooperate
   - *More choices* make it easier to persuade kids
   - Parents also need to communicate *their* feelings to kids
